### PR TITLE
Delete generated tempFile

### PR DESCRIPTION
**Pull request by markaren**
GetTempFileA is used to generate a unique id for the temp dir, but the file it generates is never deleted.

### CODE REVIEW

**Comment by markaren** [comment]
That last comit should have failed, forgot a return NULL on failure, but one can ask how the pythontest manages to create the same directory name twice (function called at the same timepoint)?

**Comment by markaren** [comment]
It is not clear to me how the python test fails..

[CoCreateGuid ](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-cocreateguid) should work no?

**Comment by robbr48** [comment]
Error code 17 means "file exists", so the problem is indeed that all jobs get the same GUID. It works with MinGW on my local machine, so it must somehow be related to how the tests are executed on GitHub. A "solution" could be to simply not run the jobs in parallel, but that doesn't solve the actual problem.

**Comment by markaren** [comment]
The paralell jobs do work. lIt is the python script that fails. Which is not running paralell..

**Comment by robbr48** [comment]
Would it be possible to test if the folder exists and, if so, re-generate the GUID?

**Comment by robbr48** [comment]
This is now resolved by #66. I used a more low-level approach and generated a random string manually and seeding the random function with the process id.

**Pull request closed without merging**
